version: '2'
services:
  keymaker-http:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./test/helpers/wait.sh rabbit:5672 -t 30 && ./test/helpers/wait.sh pg:5432 -t 30 && node_modules/.bin/knex-migrate up && npm run start-http"
    links:
      - rabbit
      - pg
    environment:
      - NODE_ENV=development
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbit
      - VAULT_ENDPOINT=http://vault:8200
      - VAULT_TOKEN=f3b7d5b3-5ebf-4474-a312-bb98e5e240c0
      - POSTGRES_POOL_MIN=1
      - POSTGRES_POOL_MAX=20
      - POSTGRES_CONNECT_STRING=postgresql://keymaker:keymaker@pg/keymaker

  keymaker-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./test/helpers/wait.sh rabbit:5672 -t 30 && ./test/helpers/wait.sh pg:5432 -t 30 && node_modules/.bin/knex-migrate up && npm run start-worker"
    links:
      - rabbit
      - pg
    environment:
      - NODE_ENV=development
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbit
      - VAULT_ENDPOINT=http://vault:8200
      - VAULT_TOKEN=f3b7d5b3-5ebf-4474-a312-bb98e5e240c0
      - POSTGRES_POOL_MIN=1
      - POSTGRES_POOL_MAX=20
      - POSTGRES_CONNECT_STRING=postgresql://keymaker:keymaker@pg/keymaker

  rabbit:
    image: rabbitmq:3.4.3-management
    ports:
      - "15672:15672"

  rabbitpuppy:
    image: meltwater/rabbit-puppy:0.3.0
    links:
      - rabbit
    volumes:
      - ./config:/config
    command: apply -b http://rabbit:15672/ -u guest -p guest -c /config/rabbit-config.yaml -w 60

  pg:
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=keymaker
      - POSTGRES_USER=keymaker
    ports:
      - "5433:5432"

